silkroad_observability:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CH_DATABASE') }}"
      host: "{{ env_var('CH_HOST') }}"
      port: "{{ env_var('CH_PORT') | int }}"
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      secure: false
      driver: "{{ env_var('CH_DRIVER', 'native') }}"
      verify: false
      connect_timeout: 10
      send_receive_timeout: 300
